platform :ios, '15.0'

target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod "MediaPipeTasksGenAI", "0.10.18"

  pod 'composeApp', :path => '../composeApp'

end
